"""Add age_group to Game model

Revision ID: bf38f3b102e2
Revises: fa974987ba24
Create Date: 2024-10-21 21:07:29.120429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf38f3b102e2'
down_revision: Union[str, None] = 'fa974987ba24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('age_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'age_group')
    # ### end Alembic commands ###
