"""Add new columns to puzzles table

Revision ID: fa974987ba24
Revises: 
Create Date: 2024-10-21 20:25:07.105276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa974987ba24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzles', sa.Column('difficulty', sa.Float(), nullable=True))
    op.add_column('puzzles', sa.Column('attempts', sa.Integer(), nullable=True))
    op.add_column('puzzles', sa.Column('time_spent', sa.Float(), nullable=True))
    op.add_column('puzzles', sa.Column('solved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzles', 'solved')
    op.drop_column('puzzles', 'time_spent')
    op.drop_column('puzzles', 'attempts')
    op.drop_column('puzzles', 'difficulty')
    # ### end Alembic commands ###
